# Generated by Django 3.2.6 on 2021-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_auto_20210804_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='finished_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type_answer',
            field=models.IntegerField(choices=[(1, 'text answer'), (2, 'one answer'), (3, 'multiple answer')], verbose_name='Тип вопроса'),
        ),
    ]
