# Generated by Django 3.2.6 on 2021-08-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0004_auto_20210805_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_type',
            field=models.CharField(choices=[('text_answer', 'Ответ текстом'), ('radio', 'Один вариант'), ('check_boxes', 'Выбор нескольких вариантов')], max_length=20, verbose_name='Тип ответа на вопрос'),
        ),
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='poll_app.questions')),
            ],
        ),
    ]
