# Generated by Django 3.2.6 on 2021-08-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_auto_20210806_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='many_options',
            field=models.ManyToManyField(null=True, related_name='answers_many_option', to='poll_app.AnswerOptions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='one_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_one_option', to='poll_app.answeroptions'),
        ),
    ]
